#!/usr/bin/env python3
"""Quantize an optimized phase trajectory and emit an ESP-IDF C++ header."""

import argparse
import json
import pathlib

import numpy as np


def wrap(value):
    return (value + np.pi) % (2 * np.pi) - np.pi


def correlation(first, second):
    first = first - np.mean(first)
    second = second - np.mean(second)
    return float(np.dot(first, second) /
                 (np.linalg.norm(first) * np.linalg.norm(second) + 1e-30))


def si_sdr(reference, estimate):
    reference = reference - np.mean(reference)
    estimate = estimate - np.mean(estimate)
    scale = np.dot(estimate, reference) / (np.dot(reference, reference) + 1e-30)
    wanted = scale * reference
    error = estimate - wanted
    return float(10 * np.log10(np.dot(wanted, wanted) /
                               (np.dot(error, error) + 1e-30)))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", help="phase optimizer data.npz")
    parser.add_argument("output", help="generated C++ header")
    parser.add_argument("--sample-rate", type=int, default=16000)
    parser.add_argument("--low-hz", type=float, default=300.0)
    parser.add_argument("--high-hz", type=float, default=3000.0)
    parser.add_argument("--xtal-hz", type=float, default=25000000.0)
    parser.add_argument("--multisynth", type=int, default=52)
    parser.add_argument("--report", default=None)
    args = parser.parse_args()

    data = np.load(args.input)
    phase = data["phase"].astype(np.float64)
    target = data["target"].astype(np.float64)
    if len(phase) != len(target):
        raise SystemExit("phase and target arrays have different lengths")

    internal_steps = wrap(np.diff(phase))
    seam_step = wrap(phase[0] - phase[-1])
    loop_steps = np.concatenate((internal_steps, [seam_step]))
    # Quantizing every increment independently turns sub-LSB error into an
    # unbounded phase random walk. Feed the residual into the next sample so
    # cumulative phase error remains close to one quantizer step.
    scale = np.pi / 127.0
    quantized = np.empty(len(loop_steps), dtype=np.int8)
    residual = 0.0
    for index, step in enumerate(loop_steps):
        shaped = step + residual
        code = int(np.clip(np.rint(shaped / scale), -127, 127))
        quantized[index] = code
        residual = shaped - code * scale
    decoded = quantized.astype(np.float64) * scale

    reconstructed_phase = np.empty_like(phase)
    reconstructed_phase[0] = phase[0]
    reconstructed_phase[1:] = phase[0] + np.cumsum(decoded[:-1])
    z = np.exp(1j * reconstructed_phase)
    frequencies = np.fft.fftfreq(len(z), 1 / args.sample_rate)
    wanted = (frequencies >= args.low_hz) & (frequencies <= args.high_hz)
    receiver = np.real(np.fft.ifft(np.fft.fft(z) * wanted))

    # Mirror main.cpp's fractional-b accumulator and the 25 MHz / MS=52
    # Si5351 mapping. This adds the second quantizer used by real firmware.
    phase_to_b = (1048575.0 * args.multisynth * args.sample_rate /
                  (2 * np.pi * args.xtal_hz))
    b_residual = 0.0
    hardware_steps = np.empty_like(decoded)
    for index, step in enumerate(decoded):
        b_residual += step * phase_to_b
        b_code = int(b_residual)  # C++ integer conversion truncates toward zero.
        b_residual -= b_code
        hardware_steps[index] = b_code / phase_to_b
    hardware_phase = np.empty_like(phase)
    hardware_phase[0] = phase[0]
    hardware_phase[1:] = phase[0] + np.cumsum(hardware_steps[:-1])
    hardware_z = np.exp(1j * hardware_phase)
    hardware_receiver = np.real(np.fft.ifft(np.fft.fft(hardware_z) * wanted))

    metrics = {
        "samples": int(len(quantized)),
        "duration_seconds": len(quantized) / args.sample_rate,
        "quantization_radians_per_lsb": float(np.pi / 127.0),
        "phase_step_error_rms": float(np.sqrt(np.mean((decoded - loop_steps) ** 2))),
        "phase_step_error_max": float(np.max(np.abs(decoded - loop_steps))),
        "cumulative_phase_error_max": float(np.max(np.abs(
            np.cumsum(decoded[:-1] - internal_steps)))),
        "receiver_correlation": correlation(target, receiver),
        "receiver_si_sdr_db": si_sdr(target, receiver),
        "si5351_phase_to_b_factor": float(phase_to_b),
        "hardware_receiver_correlation": correlation(target, hardware_receiver),
        "hardware_receiver_si_sdr_db": si_sdr(target, hardware_receiver),
        "seam_step_radians": float(seam_step),
        "seam_step_quantized": int(quantized[-1]),
    }

    output = pathlib.Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as header:
        header.write("// Generated by simulate/export_phase_firmware.py.\n")
        header.write("// Constant-envelope 16 ksample/s experimental trajectory.\n")
        header.write("#ifndef PHASE_OPTIMIZED_DATA_H\n")
        header.write("#define PHASE_OPTIMIZED_DATA_H\n\n")
        header.write("#include <stdint.h>\n\n")
        header.write("static constexpr uint32_t optimized_phase_sample_rate_hz = ")
        header.write(f"{args.sample_rate}U;\n")
        header.write("static constexpr float optimized_phase_step_scale = ")
        header.write(f"{np.pi / 127.0:.12f}f;\n")
        header.write("alignas(4) static const int8_t optimized_phase_steps[] = {\n")
        for start in range(0, len(quantized), 24):
            values = ", ".join(str(int(value)) for value in quantized[start:start + 24])
            header.write(f"  {values},\n")
        header.write("};\n")
        header.write("static constexpr uint32_t optimized_phase_steps_len =\n")
        header.write("    sizeof(optimized_phase_steps) / sizeof(optimized_phase_steps[0]);\n\n")
        header.write("#endif\n")

    report = pathlib.Path(args.report) if args.report else output.with_suffix(".json")
    with report.open("w", encoding="utf-8") as destination:
        json.dump(metrics, destination, indent=2)
        destination.write("\n")
    print(json.dumps(metrics, indent=2))
    print(f"Wrote {output} and {report}")


if __name__ == "__main__":
    main()
