#!/usr/bin/env python3
"""
Generate 257-tap Hilbert filter coefficients for Hi-Fi SSB
50-15000 Hz bandwidth at 32 kHz sample rate
Uses Blackman-Harris window for >90 dB stopband rejection

Output: C array ready to paste into polar_mod.cpp
"""

import numpy as np

# Filter parameters
N_TAPS = 257          # Must be odd
CENTER = N_TAPS // 2  # 128
Fs = 32000            # Sample rate

print(f"// {N_TAPS}-tap Hilbert Transform Coefficients (Blackman-Harris windowed)")
print(f"// Sample rate: {Fs} Hz, Passband: 50-15000 Hz")
print(f"// Automatically generated by hilbert_coeffs.py")
print(f"// Paste into polar_mod.cpp as h_hifi[{N_TAPS}]")
print()
print(f"static const float h_hifi[{N_TAPS}] = {{")

# Blackman-Harris window
n = np.arange(N_TAPS)
w = (0.35875 - 0.48829 * np.cos(2 * np.pi * n / (N_TAPS - 1)) +
     0.14128 * np.cos(4 * np.pi * n / (N_TAPS - 1)) -
     0.01168 * np.cos(6 * np.pi * n / (N_TAPS - 1)))

# Ideal Hilbert: h[k] = 2/(pi*k) for odd k, 0 for even k
# Centered at tap 128
h = np.zeros(N_TAPS)
for k in range(N_TAPS):
    offset = k - CENTER
    if offset == 0:
        h[k] = 0.0
    elif offset % 2 != 0:  # odd offsets only
        h[k] = (2.0 / (np.pi * offset)) * w[k]
    else:
        h[k] = 0.0

# Normalize so peak coefficient = 1.0 (optional, prevents overflow)
peak = np.max(np.abs(h))
# Don't normalize - the runtime code expects raw coefficients
# if peak > 0:
#     h = h / peak

# Print as C array
for i in range(N_TAPS):
    if i % 8 == 0:
        print("  ", end="")
    print(f"{h[i]:10.6f}f,", end="")
    if i % 8 == 7 or i == N_TAPS - 1:
        print()

print("};")
print()

# Verify frequency response
freqs = np.fft.fftfreq(N_TAPS, 1.0/Fs)
H = np.fft.fft(h)
magnitude = np.abs(H)
phase = np.angle(H)

# Print key frequency points
print("// Frequency Response Verification:")
for f_test in [50, 100, 300, 1000, 3000, 5000, 10000, 15000, 16000]:
    idx = np.argmin(np.abs(np.abs(freqs) - f_test))
    mag_db = 20 * np.log10(magnitude[idx] + 1e-10)
    phase_deg = np.degrees(phase[idx])
    print(f"// {f_test:6d} Hz: {mag_db:+7.2f} dB, phase: {phase_deg:+7.2f}°")
