#!/usr/bin/env python3
"""
Convert audio file (OGG, WAV, MP3, etc.) to C header array for RP2350 firmware.
Converts to 32kHz mono 16-bit PCM format compatible with audio_data.h format.

Usage:
    python3 wav_to_c.py <input_audio_file> <output_header_file> [array_name]

Example:
    python3 wav_to_c.py Winston_Churchill.ogg audio_data3.h wav_data3
"""

import sys
import os
import numpy as np

try:
    import soundfile as sf
except ImportError:
    print("Error: soundfile library not installed.")
    print("Install with: pip3 install soundfile numpy")
    sys.exit(1)


def convert_audio_to_c(input_file, output_file, array_name="wav_data3", target_sr=32000, max_duration=None):
    """Convert audio file to C header with int16_t array."""
    
    print(f"Reading audio file: {input_file}")
    
    # Read audio file
    try:
        data, samplerate = sf.read(input_file, dtype='float32')
    except Exception as e:
        print(f"Error reading audio file: {e}")
        sys.exit(1)
    
    # Convert to mono if stereo
    if len(data.shape) > 1:
        print(f"Converting {data.shape[1]} channels to mono")
        data = np.mean(data, axis=1)
    
    print(f"Original sample rate: {samplerate} Hz")
    print(f"Original duration: {len(data)/samplerate:.2f} seconds")
    print(f"Original samples: {len(data)}")
    
    # Trim to max duration if specified
    if max_duration is not None:
        max_samples = int(max_duration * samplerate)
        if len(data) > max_samples:
            print(f"Trimming to {max_duration} seconds ({max_samples} samples)")
            data = data[:max_samples]
    
    # Resample to target sample rate if needed
    if samplerate != target_sr:
        print(f"Resampling from {samplerate} Hz to {target_sr} Hz")
        # Simple linear interpolation resampling
        duration = len(data) / samplerate
        new_length = int(duration * target_sr)
        old_indices = np.arange(0, len(data))
        new_indices = np.linspace(0, len(data) - 1, new_length)
        data = np.interp(new_indices, old_indices, data)
        samplerate = target_sr
    
    print(f"Resampled samples: {len(data)}")
    
    # Normalize to use full 16-bit range (but prevent clipping)
    max_val = np.max(np.abs(data))
    if max_val > 0:
        # Normalize to 90% of full scale to prevent clipping
        data = data * (0.9 / max_val)
    
    # Convert to 16-bit integers
    data_int16 = (data * 32767.0).astype(np.int16)
    
    # Print statistics
    print(f"Max amplitude: {np.max(np.abs(data_int16))}")
    print(f"DC offset: {np.mean(data_int16):.2f}")
    
    # Write C header file
    print(f"Writing C header: {output_file}")
    
    header_guard = os.path.basename(output_file).replace('.', '_').upper()
    
    with open(output_file, 'w') as f:
        f.write(f"#ifndef {header_guard}\n")
        f.write(f"#define {header_guard}\n")
        f.write(f"\n")
        f.write(f"#include <stdint.h>\n")
        f.write(f"\n")
        f.write(f"// {os.path.basename(input_file)} converted to C array\n")
        f.write(f"// Sample rate: {target_sr} Hz, mono, 16-bit PCM\n")
        f.write(f"// Samples: {len(data_int16)}, Duration: {len(data_int16)/target_sr:.2f}s\n")
        f.write(f"// Generated by wav_to_c.py\n")
        f.write(f"\n")
        
        # Write array declaration
        f.write(f"const int16_t {array_name}[] = {{\n")
        
        # Write data in chunks of 20 samples per line for readability
        samples_per_line = 20
        for i in range(0, len(data_int16), samples_per_line):
            chunk = data_int16[i:i+samples_per_line]
            line = "  " + ", ".join(str(x) for x in chunk)
            if i + samples_per_line < len(data_int16):
                line += ","
            f.write(line + "\n")
        
        f.write(f"}};\n")
        f.write(f"\n")
        f.write(f"const uint32_t {array_name}_len = {len(data_int16)};\n")
        f.write(f"\n")
        f.write(f"#endif\n")
    
    # Calculate file size estimate
    file_size_kb = len(data_int16) * 2 / 1024  # int16 = 2 bytes per sample
    print(f"\nConversion complete!")
    print(f"Output file: {output_file}")
    print(f"Array size: {len(data_int16)} samples ({file_size_kb:.1f} KB in flash)")
    print(f"\nTo use this in firmware:")
    print(f"1. Copy {output_file} to firmware_ssb_ad9850/src/")
    print(f"2. Include it in main.cpp: #include \"{os.path.basename(output_file)}\"")
    print(f"3. Update get_wav_sample() to select based on wav_select")
    print(f"4. Update CAT command '*a' handler to support 3 options")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    array_name = sys.argv[3] if len(sys.argv) > 3 else "wav_data3"
    max_duration = int(sys.argv[4]) if len(sys.argv) > 4 else None
    
    if not os.path.exists(input_file):
        print(f"Error: Input file not found: {input_file}")
        sys.exit(1)
    
    convert_audio_to_c(input_file, output_file, array_name, max_duration=max_duration)
